In [5]:
import numpy as np
a=np.zeros(4,dtype=int)
a.shape=(2,2)
a

array([[0, 0],
       [0, 0]])

In [6]:
b=np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [7]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
z = np.linspace(2, 4, 5)  # From 2 to 4, with 5 elements
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [14]:
z=np.array([[1,2],[3,4]])
z[1,0]
z[0]
z[0,:]
z.argmax()# Returns the index of the maximal element
z.cumsum()            # Cumulative sum of the elements of A
z.cumprod()           # Cumulative product of the elements of A
z.var()
z.std()
z.T# Equivalent to A.transpose()

array([[1, 3],
       [2, 4]])

In [15]:
z=np.linspace(2,4,5)
z.searchsorted(2.2)#If z is a nondecreasing array, 
#then z.searchsorted(a) returns the 
#index of the first element of z that is >= a

1

In [16]:
#The algebraic operators +, -, *, / and ** 
#all act element-wise on arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b

array([ 6,  8, 10, 12])

In [17]:
# @ symbol for matrix multiplication
A = np.ones((2, 2))
B = np.ones((2, 2))
A @ B

array([[2., 2.],
       [2., 2.]])

In [19]:
#use @ to take the inner product of two flat arrays
A = np.array((1, 2))
B = np.array((10, 20))
A @ B

50

In [21]:
a = np.random.randn(3)
a
b = a
b[0] = 0.0
a

array([0.        , 0.46534144, 0.81925222])

In [23]:
a = np.random.randn(3)
a
b = np.empty_like(a)  # empty array with same shape as a
np.copyto(b, a)  # copy to b from a,deep copy
b
b[:]=1
b

array([1., 1., 1.])

In [24]:
#The NumPy function np.where provides a vectorized alternative:
import numpy as np

x = np.random.randn(4)
x
np.where(x > 0, 1, 0)  # Insert 1 if x > 0 true, otherwise 0

array([1, 1, 1, 1])

In [25]:
def f(x): return 1 if x > 0 else 0

f = np.vectorize(f)
f(x)                # Passing the same vector x as in the previous example

array([1, 1, 1, 1])

In [26]:
A = np.array([[1, 2], [3, 4]])

np.linalg.det(A)           # Compute the determinant

-2.0000000000000004

In [27]:
np.linalg.inv(A)           # Compute the inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])